[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = ">=3.8,<4.0"
scipy = "*"
matplotlib = "^3.5.2"
numpy = "^1.23.1"
